// <auto-generated />
using System;
using Blazor_test14.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blazor_test14.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blazor_test14.Shared.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "本文1",
                            CreateDate = new DateTime(2023, 12, 28, 21, 0, 46, 950, DateTimeKind.Local).AddTicks(324),
                            Title = "タイトル1",
                            UpdateDate = new DateTime(2023, 12, 28, 21, 0, 46, 950, DateTimeKind.Local).AddTicks(333)
                        },
                        new
                        {
                            Id = 2,
                            Content = "本文2",
                            CreateDate = new DateTime(2023, 12, 28, 21, 0, 46, 950, DateTimeKind.Local).AddTicks(334),
                            Title = "タイトル2",
                            UpdateDate = new DateTime(2023, 12, 28, 21, 0, 46, 950, DateTimeKind.Local).AddTicks(335)
                        },
                        new
                        {
                            Id = 3,
                            Content = "本文3",
                            CreateDate = new DateTime(2023, 12, 28, 21, 0, 46, 950, DateTimeKind.Local).AddTicks(336),
                            Title = "タイトル3",
                            UpdateDate = new DateTime(2023, 12, 28, 21, 0, 46, 950, DateTimeKind.Local).AddTicks(336)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
